export const FETCH_MOVIES = 'FETCH_MOVIES';
export const RECEIVE_MOVIES = 'RECEIVE_MOVIES';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
